.gitlab-ci.yml: install individual packages instead of build-base
build-base additionally installs fortify-headers, which causes
LTO builds to fail:

/builds/tuankiet65/knocknock/third_party/fmt/include/fmt/format-inl.h: In function 'snprintf_float.constprop':
/usr/include/fortify/stdio.h:95:27: error: inlining failed in call to always_inline 'snprintf': function body can be overwritten at link time
   95 | _FORTIFY_FN(snprintf) int snprintf(char *__s, size_t __n, const char *__f, ...)
      |                           ^
/builds/tuankiet65/knocknock/third_party/fmt/include/fmt/format-inl.h:1157:36: note: called from here
 1157 |                      ? snprintf_ptr(begin, capacity, format, precision, value)
      |                                    ^
/usr/include/fortify/stdio.h:95:27: error: inlining failed in call to always_inline 'snprintf': function body can be overwritten at link time
   95 | _FORTIFY_FN(snprintf) int snprintf(char *__s, size_t __n, const char *__f, ...)
      |                           ^
/builds/tuankiet65/knocknock/third_party/fmt/include/fmt/format-inl.h:1158:36: note: called from here
 1158 |                      : snprintf_ptr(begin, capacity, format, value);
      |                                    ^
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status